clear; close all; clc;

ground_reaction_forces('collegiate_soccer_player_8mps.csv', ...
    'Collegiate Soccer Player at 8 m/s (17.9 mph)');
ground_reaction_forces('national_champion_sprinter_26mph.csv', ...
    'National Champion Sprinter at 26+ mph');
ground_reaction_forces('marathon_12mph.csv', ...
    'Marathoner at 12.3 mph');
ground_reaction_forces('ncaa_sprinter_25mph.csv', ...
    'NCAA Sprinter at 25 mph');

